### ISSUE TITLE
关于这个插件的一些建议

### ISSUE THREAD

**Issue by YestermorrowONill** [waterovo/trilium-simple-mind-map#1]
首先我得感谢作者，这个插件做的非常的好，达成了我一直以来在trilium中画思维导图的夙愿。相较于作者之前做的js-mind的集成，这款插件显然功能更强，效果也更加美观。
其次，关于这个插件我有两个不成熟的想法，作者如果觉得合适的话可以考虑一下：
1. 思维导图下面的json其实没啥必要显示，可以的话可以隐藏掉，或者做成可配置的，用户可以选择隐藏或者不隐藏；
2. 思维导图中的节点，是否能链接当前trilium中的其他笔记？

**Comment by waterovo** [comment]
早上好
1.json隐藏目前还没有解决方案，会影响其他标签页
2.节点链接笔记已经实现，只是还没发布release，可以直接下载源码体验

**Comment by YestermorrowONill** [comment]
试了一下，这个节点链接的功能确实可以。给作者点个赞
另外还有个细节我不得不称赞一句，就是当前思维导图笔记没有因为与其他笔记有链接而增加关系，这一点我还是相当认同的。
