### ISSUE TITLE
分享链接不能渲染

### ISSUE THREAD

**Issue by 13653216371** [waterovo/trilium-simple-mind-map#12]
#
![image](https://github.com/user-attachments/assets/e977ed0d-854e-4239-a846-bd6f4df3d396)

**Comment by waterovo** [comment]
插件只支持在trilium中渲染，如需分享请使用左上角菜单的导出图片附件，会在子笔记生成一个svg图片
如果您确实需要此功能可以考虑升级trilium-next使用集成的mindmap笔记类型

**Comment by 13653216371** [comment]
svg无法看备注内容。。倒是可以打开超链接，可以凑合着使用，如果在分享界面可以渲染就太好了

**Comment by waterovo** [comment]
> svg无法看备注内容。。倒是可以打开超链接，可以凑合着使用，如果在分享界面可以渲染就太好了

下个版本更新

**Comment by waterovo** [comment]
> svg无法看备注内容。。倒是可以打开超链接，可以凑合着使用，如果在分享界面可以渲染就太好了

已更新

**Comment by 13653216371** [comment]
> > svg无法看备注内容。。倒是可以打开超链接，可以凑合着使用，如果在分享界面可以渲染就太好了
> 
> 已更新

测试OK，很开门
