### ISSUE TITLE
是否可以在包含中展示哇

### ISSUE THREAD

**Issue by MASK-LI** [waterovo/trilium-simple-mind-map#2]
![image](https://github.com/waterovo/trilium-simple-mind-map/assets/68579782/b7c184b6-0c14-4040-8ffb-da54d9a96dca)
我看了新版的已经可以实现笔记连接了,跳转可以多一个选择原窗口，不新建麽
![image](https://github.com/waterovo/trilium-simple-mind-map/assets/68579782/4172ac10-f39c-407e-b67f-26fa44673b4f)
如果其它笔记中包含中也能够展示就好了，并且超链接点击能够正常跳转

**Comment by waterovo** [comment]
包含展示用生成的图片笔记吧，超链接是由simple-mind-map实现的，目前无法更改😭

**Comment by waterovo** [comment]
我添加了一个方法，现在笔记超链接会在原窗口打开，其他超链接保持原样

**Comment by MASK-LI** [comment]
> 我添加了一个方法，现在笔记超链接会在原窗口打开，其他超链接保持原样

好滴 谢谢 hhh
