### ISSUE TITLE
设置SHOW_SOURCE = false后笔记标题处属性无法编辑

### ISSUE THREAD

**Issue by YestermorrowONill** [waterovo/trilium-simple-mind-map#4]
设置SHOW_SOURCE = false后虽然JSON源码不再显示了，但是相应的包括笔记标题在内的笔记顶层的属性也无法显示和编辑了

**Comment by waterovo** [comment]
是的，可以通过左上角菜单的【Exit Full Tab】退出Full Tab后编辑，
