### ISSUE TITLE
因为加入图片导致思维导图笔记加载变慢

### ISSUE THREAD

**Issue by YestermorrowONill** [waterovo/trilium-simple-mind-map#7]
我看笔记中的JSON源码是以data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAroAAAK6CAIAAABZn2hOAAAgAElEQVR4Ae...这种格式呈现的，我在笔记中加了两张图片，笔记加载就已经比较卡顿了，如果是更多张，想必会更慢。能否支持引入笔记中的其他图片附件的形式来加入图片？这样的话应该就能缩减JSON的体积了

**Comment by waterovo** [comment]
可以用在线图片url链接，可以复制图片笔记的url链接

**Comment by waterovo** [comment]
该功能目前不再进行更改，建议将图片导入trilium后复制图片链接插入到导图中
